services:
  db:
    container_name: postgres-0
    image: postgres-0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Un544kF0
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      -db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: